### ISSUE TITLE
Problem with strict mode?

### ISSUE THREAD

**Issue by cofilippo** [lancedikson/bowser#187] opened 2017-07-28 15:26 UTC
Hi,

I'm tring to create a browser filter based on bowser. I'm having some problems with bowser when using unsupported browsers when using strict mode.

I'm passing the mobile property if bowser detects mobile or tablet, otherwise I pass the desktop property of the following json:

`{"desktop":{"chrome":"57","msedge":"14","firefox":"53","msie":"11","opera":"45","safari":"10"},"mobile":{"chrome":"59","and_ff":"54","android":"4.4.3-4.4.4","msie":"11","ios":"10.0-10.2","samsungBrowser":"5","msedge":"14"}}`

Somehow enabling strict doesn't actually force bowser to return true if the browser is not in the object. For example, opera mini (ua: window.navigator.userAgent of the browser is: `Mozilla/5.0 (linux; U; Android; GT-I9300 Build/JSS15J) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30 OPR/28.0.2254 119224`) is detected as opera and mobile, yet returns false if i run isUnsupportedBrowser as follows

`bowser.isUnsupportedBrowser(supportedBrowsers[browserClass], true, window.navigator.userAgent)`

The supportedBrowsers variable is the JSON. Browsers which are not in the list are not supported at all.

Did I miss something, or is strict mode not working as it should?

**Comment by lancedikson** [comment] 2017-08-19 16:33
@cofilippo, hey, sorry for the late response. The problem is that bowser doesn't support platform splitting that you're trying to use. It only accepts a list of browsers and doesn't care what the platform is. Maybe, later we will apply some new functionality of it, that gives an opportunity to split by platform.

**Comment by cofilippo** [comment] 2017-08-29 11:01
Hello Lance,

Thanks for getting back to me.

In the end we chose to implement browser detection based on  feature detection, so I haven't actually gotten any further with this issue.

However, after reading your response another time I wonder if I explained things clearly enough, and just to make sure that it really was on my end, I'd like to rephrase the question.

Here's the code I used with Bowser:

```
import { autoinject } from "aurelia-dependency-injection";
import { HttpClient } from "aurelia-fetch-client";
import * as bowser from "bowser";
@autoinject
export default class BrowserCheck {

  constructor(private httpClient: HttpClient) { }

  public async check(): Promise<void> {

    let supportedBrowsers;
    try {
      supportedBrowsers = await this.loadJSON("../old_browsers/supported-browsers.json");
    } catch (error) {
      this.redirectToNotSupportedBrowserPage();
      return;
    }

    let browserClass = "desktop";
    if (bowser.mobile || bowser.tablet) {
      browserClass = "mobile";
    }

    if (bowser.isUnsupportedBrowser(supportedBrowsers[browserClass], false, window.navigator.userAgent)) {
      this.redirectToNotSupportedBrowserPage();
      return;
    }
  }

  public redirectToNotSupportedBrowserPage(): void {
    window.location.replace("not-supported-browser.html");
  }

  private async loadJSON(path: string): Promise<any> {
    const response = await this.httpClient.fetch(path);
    if (response.status !== 200) {
      throw new Error("Response status code (${response.status}) doesn\'t indicate success");
    }
    return await response.json();
  }
}

```

So it either passes `{"chrome":"57","msedge":"14","firefox":"53","msie":"11","opera":"45","safari":"10"}` to bowser when no mobile device is detected or `{"chrome":"59","and_ff":"54","android":"4.4.3-4.4.4","msie":"11","ios":"10.0-10.2","samsungBrowser":"5","msedge":"14"}` to bowser when a mobile device is detected, not the complete JSON in full.

So given a mobile device and the object associated with the mobile devices in the JSON being passed to isUnsupportedBrowser in strict mode, shouldn't it return true? 

It worked fine for IE, Chrome and FireFox, just not Opera and some versions of Edge. (but the Edge thing was probably due to version numbers of installed browsers on my end, so I left it out)

**Comment by lancedikson** [comment] 2019-01-19 15:08
Closing this one, seems a bit obsolete

**Closed by lancedikson** 2019-01-19 15:08 UTC
